require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DeparturesController, type: :controller do
  before(:each) do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    sign_in User.create(login: 'admin', password: 'admin123') # Using factory girl as an example
  end
  # This should return the minimal set of attributes required to create a valid
  # Departure. As you add validations to Departure, be sure to
  # adjust the attributes here as well.
  let(:monitor) { Stuff.create!(name: 'Monitor', amount: 50) }
  let(:valid_attributes) do
    {stuff_id: monitor.id, amount: 10}
  end

  let(:invalid_attributes) do
    {stuff_id: monitor.id, amount: ''}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeparturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all departures as @departures" do
      departure = Departure.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:departures)).to eq([departure])
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Departure" do
        expect {
          post :create, {:departure => valid_attributes}, valid_session
        }.to change(Departure, :count).by(1)
      end

      it "assigns a newly created departure as @departure" do
        post :create, {:departure => valid_attributes}, valid_session
        expect(assigns(:departure)).to be_a(Departure)
        expect(assigns(:departure)).to be_persisted
      end
    end

    context "with invalid params" do
      it "insufficient amount for departure" do
        expect {
          post :create, {:departure => valid_attributes}, valid_session
        }.to change(Departure, :count).by(1)
      end
    end
  end

end
